{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "platform-poc-api.serviceAccountName" . }}
  labels:
    {{- include "platform-poc-api.labels" . | nindent 4 }}
automountServiceAccountToken: false
{{- end }}
