# Generated by Django 6.0.5 on 2026-05-21 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ABTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('variant_a_name', models.CharField(default='Control', max_length=64)),
                ('variant_b_name', models.CharField(default='Variant', max_length=64)),
                ('split_percentage', models.IntegerField(default=50, help_text='% of traffic for variant_b')),
                ('variant_a_conversions', models.IntegerField(default=0)),
                ('variant_a_views', models.IntegerField(default=0)),
                ('variant_b_conversions', models.IntegerField(default=0)),
                ('variant_b_views', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeploymentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(help_text='Git commit SHA or semver', max_length=64)),
                ('strategy', models.CharField(choices=[('blue_green', 'Blue-Green'), ('canary', 'Canary'), ('feature_flag', 'Feature Flag'), ('ab_test', 'A/B Test')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('rolled_back', 'Rolled Back')], default='pending', max_length=20)),
                ('canary_percentage', models.IntegerField(default=0, help_text='For canary: current traffic %')),
                ('error_rate', models.FloatField(default=0.0, help_text='Observed error rate during rollout')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('disabled', 'Disabled'), ('enabled', 'Enabled'), ('rolling_out', 'Rolling Out')], default='disabled', max_length=20)),
                ('rollout_percentage', models.IntegerField(default=0, help_text='0-100: percentage of users to enable for')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
